### PR TITLE
setup project

### PR DESCRIPTION
**Pull request by bmassioui**

### CODE REVIEW

**Comment by bmassioui** [comment]
@mbouchaib 
this PR contains all changes related to #4 UserStory

**Comment by bmassioui** [comment]
@mbouchaib can you approve this PR and Complete it :)

**Comment by mbouchaib** [comment]
> 

Ok great :)

Can you pull staging and main ?

**Review by mbouchaib — APPROVED** [review]
Ok great

**Comment by bmassioui** [comment]
> > 
> 
> Ok great :)
> 
> Can you pull staging and main ?

@mbouchaib OK :)

**Pull request merged**
